# Prepare internal haplotype database
#
# This script reads the curated haplotype database from Excel and stores it as
# package-internal R code in R/internal_haplotype_database.R.

library(readxl)
library(dplyr)
library(stringr)

normalize_sequence <- function(x) {
  x |>
    as.character() |>
    stringr::str_replace_all("\u00A0", "") |>
    stringr::str_replace_all("\\s+", "") |>
    stringr::str_to_upper() |>
    dplyr::na_if("")
}

clean_text <- function(x) {
  x <- as.character(x)
  x <- stringr::str_replace_all(x, "\u00A0", " ")
  x <- stringr::str_squish(x)
  dplyr::na_if(x, "")
}

normalize_locus <- function(x) {
  x <- as.character(x)
  x <- stringr::str_replace_all(x, "\u00A0", " ")
  x <- stringr::str_squish(x)

  rs_list <- stringr::str_extract_all(
    stringr::str_to_lower(x),
    "rs\\s*\\d+",
    simplify = FALSE
  )

  out <- vapply(
    rs_list,
    function(z) {
      z <- z[!is.na(z)]

      if (length(z) == 0) {
        NA_character_
      } else {
        z <- stringr::str_replace_all(z, "\\s+", "")
        tail(z, 1)
      }
    },
    character(1)
  )

  out <- ifelse(is.na(out), stringr::str_to_lower(x), out)
  dplyr::na_if(out, "")
}

clean_allele <- function(x) {
  x |>
    clean_text() |>
    stringr::str_to_upper() |>
    dplyr::na_if("")
}

normalize_colname <- function(x) {
  x |>
    as.character() |>
    stringr::str_replace_all("\u00A0", " ") |>
    stringr::str_squish() |>
    stringr::str_to_lower()
}

get_column <- function(df, candidates) {
  names_norm <- normalize_colname(names(df))
  candidates_norm <- normalize_colname(candidates)

  pos <- match(candidates_norm, names_norm)
  pos <- pos[!is.na(pos)]

  if (length(pos) == 0) {
    stop(
      "None of these columns were found: ",
      paste(candidates, collapse = ", ")
    )
  }

  names(df)[pos[1]]
}

r_string <- function(x) {
  ifelse(
    is.na(x),
    "NA_character_",
    paste0(
      '"',
      gsub('"', '\\\"', gsub('\\\\', '\\\\\\\\', as.character(x))),
      '"'
    )
  )
}

raw_db <- readxl::read_excel(
  path = "data-raw/database.xlsx",
  sheet = "haplotype_database",
  col_types = "text"
)

col_target_snp <- get_column(raw_db, c("TargetSNP"))
col_target_snp_allele <- get_column(raw_db, c("TargetSNP_allele"))
col_haplotype <- get_column(raw_db, c("Haplotype"))
col_sequence <- get_column(raw_db, c("Sequence"))
col_polymorphic_sites <- get_column(raw_db, c("Polymorphic_sites"))
col_position_grch38 <- get_column(raw_db, c("Position_GRCh38"))

haplotype_database <- raw_db |>
  dplyr::transmute(
    TargetSNP = normalize_locus(.data[[col_target_snp]]),
    TargetSNP_allele = clean_allele(.data[[col_target_snp_allele]]),
    Haplotype = clean_text(.data[[col_haplotype]]),
    Sequence = clean_text(.data[[col_sequence]]),
    Polymorphic_sites = clean_text(.data[[col_polymorphic_sites]]),
    Position_GRCh38 = clean_text(.data[[col_position_grch38]])
  ) |>
  dplyr::filter(
    !is.na(.data$TargetSNP),
    .data$TargetSNP != "",
    !is.na(.data$TargetSNP_allele),
    .data$TargetSNP_allele != "",
    !is.na(.data$Haplotype),
    .data$Haplotype != "",
    !is.na(.data$Sequence),
    .data$Sequence != "",
    !is.na(.data$Polymorphic_sites),
    .data$Polymorphic_sites != "",
    !is.na(.data$Position_GRCh38),
    .data$Position_GRCh38 != ""
  ) |>
  dplyr::distinct()

# The normalized sequence key is only used temporarily to validate duplicates.
duplicated_keys <- haplotype_database |>
  dplyr::mutate(
    sequence_key = normalize_sequence(.data$Sequence)
  ) |>
  dplyr::count(.data$TargetSNP, .data$sequence_key, name = "n") |>
  dplyr::filter(.data$n > 1)

if (nrow(duplicated_keys) > 0) {
  stop(
    "The haplotype database contains duplicated TargetSNP + Sequence keys. ",
    "Please fix data-raw/database.xlsx before creating the internal database."
  )
}

lines <- c(
  "# Internal haplotype database generated from data-raw/database.xlsx",
  "# Do not edit this file manually. Edit data-raw/database.xlsx and rerun data-raw/haplotype_database.R instead.",
  "",
  "haplotype_database <- data.frame("
)

for (column in names(haplotype_database)) {
  lines <- c(
    lines,
    paste0(
      "  ", column, " = c(",
      paste(r_string(haplotype_database[[column]]), collapse = ", "),
      "),"
    )
  )
}

lines <- c(
  lines,
  "  stringsAsFactors = FALSE",
  ")"
)

writeLines(lines, "R/internal_haplotype_database.R")
