#' Create a consensus Familias TXT from replicate review Excel files
#'
#' Reads several per-sample review Excel files generated by the package, combines
#' the haplotypes observed across replicates, and writes a one-row Familias-style TXT.
#'
#' @param reports_dir Directory containing the replicate review Excel files.
#' @param output_txt Output TXT filename or path. If relative, it is written inside
#'   `reports_dir`. If `NULL`, the file is not written.
#' @param loci_order Character vector with the expected loci and output order.
#'   Defaults to `default_loci_order()`.
#' @param max_alleles Maximum number of unique alleles allowed per locus.
#' @param sheet Excel sheet to read from each review file.
#' @param pattern File pattern used to find Excel files.
#' @param value_columns Two columns containing the haplotype values to combine.
#'   Defaults to `Haplotype_1` and `Haplotype_2`.
#' @param sample_id_prefix Prefix used for the consensus sample id.
#'
#' @return A list with the consensus table, combined reports, conflict loci,
#'   missing loci, input files and output path.
#' @examples
#' \dontrun{
#' res <- create_consensus_txt(
#'   reports_dir = "path/to/replicate_review_excels"
#' )
#'
#' res$consensus_txt
#' res$conflicts
#' res$missing_loci
#' }
#' @export
create_consensus_txt <- function(
    reports_dir,
    output_txt = "consensus.txt",
    loci_order = default_loci_order(),
    max_alleles = 2,
    sheet = "Final_calls",
    pattern = "\\.xlsx$",
    value_columns = c("Haplotype_1", "Haplotype_2"),
    sample_id_prefix = "consensus_"
) {
  if (!dir.exists(reports_dir)) {
    stop("`reports_dir` does not exist: ", reports_dir)
  }

  if (length(value_columns) != 2) {
    stop("`value_columns` must contain exactly two column names.")
  }

  reports <- list.files(
    path = reports_dir,
    pattern = pattern,
    full.names = TRUE
  )

  reports <- reports[!grepl("^~\\$", basename(reports))]
  reports <- reports[grepl("^review_", basename(reports), ignore.case = TRUE)]

  if (length(reports) == 0) {
    stop("No review Excel reports were found in: ", reports_dir)
  }

  report_list <- vector("list", length(reports))

  for (i in seq_along(reports)) {
    report <- readxl::read_excel(
      path = reports[[i]],
      sheet = sheet,
      col_types = "text"
    )

    locus_column <- if ("TargetSNP" %in% names(report)) {
      "TargetSNP"
    } else {
      get_column(report, c("TargetSNP"))
    }

    required_columns <- c("sample_id", locus_column, value_columns)
    missing_columns <- setdiff(required_columns, names(report))

    if (length(missing_columns) > 0) {
      stop(
        "The file `", basename(reports[[i]]),
        "` is missing required columns: ",
        paste(missing_columns, collapse = ", ")
      )
    }

    report$TargetSNP <- normalize_locus(report[[locus_column]])
    report$replicate <- paste0("rep", i)
    report$source_consensus_file <- basename(reports[[i]])

    report_list[[i]] <- report
  }

  df <- dplyr::bind_rows(report_list)

  first_sample_id <- df$sample_id[!is.na(df$sample_id) & df$sample_id != ""][1]

  if (is.na(first_sample_id) || length(first_sample_id) == 0) {
    first_sample_id <- "unknown_sample"
  }

  consensus_table <- data.frame(
    matrix(
      NA_character_,
      nrow = 1,
      ncol = length(loci_order) + 1
    ),
    stringsAsFactors = FALSE
  )

  colnames(consensus_table) <- c("sample_id", loci_order)
  consensus_table[1, "sample_id"] <- paste0(sample_id_prefix, first_sample_id)

  conflict_loci <- list()
  missing_loci <- character(0)

  for (locus in loci_order) {
    alleles <- df |>
      dplyr::filter(.data$TargetSNP == locus) |>
      dplyr::select(dplyr::all_of(value_columns)) |>
      unlist(use.names = FALSE)

    alleles <- as.character(alleles)
    alleles <- alleles[!is.na(alleles)]
    alleles <- trimws(alleles)
    alleles <- alleles[alleles != "" & alleles != "NA"]
    alleles <- unique(alleles)

    if (length(alleles) == 0) {
      missing_loci <- c(missing_loci, locus)
    } else if (length(alleles) == 1) {
      consensus_table[1, locus] <- paste(alleles, alleles, sep = ",")
    } else if (length(alleles) <= max_alleles) {
      consensus_table[1, locus] <- paste(alleles, collapse = ",")
    } else {
      conflict_loci[[locus]] <- alleles
    }
  }

  if (length(conflict_loci) > 0) {
    conflicts <- data.frame(
      locus = names(conflict_loci),
      n_alleles = vapply(conflict_loci, length, integer(1)),
      alleles = vapply(conflict_loci, paste, character(1), collapse = ","),
      stringsAsFactors = FALSE
    )
  } else {
    conflicts <- data.frame(
      locus = character(0),
      n_alleles = integer(0),
      alleles = character(0),
      stringsAsFactors = FALSE
    )
  }

  output_path <- NULL

  if (!is.null(output_txt)) {
    output_path <- output_txt

    if (!grepl("[/\\\\]", output_txt)) {
      output_path <- file.path(reports_dir, output_txt)
    }

    utils::write.table(
      consensus_table,
      file = output_path,
      sep = "\t",
      quote = FALSE,
      col.names = TRUE,
      row.names = FALSE,
      na = ""
    )
  }

  list(
    consensus_txt = consensus_table,
    combined_reports = df,
    conflicts = conflicts,
    missing_loci = missing_loci,
    reports = reports,
    output_txt = output_path
  )
}
